### ISSUE TITLE
[Access Resources] Share Business Logic

### ISSUE THREAD

**Issue by econesag** [devonfw/hangar#326]

**Comment by airherna** [comment]
This should make improvements in the access of resources like the repos, adding calls to the google cloud CLI to improve the number of resources and url generation.

Right now the IDE and the pipelines are correctly opened, but we have a problem when dealing with projects created with quickstart, because the repos change from "Backend" and "Frontend" to "wayat-flutter" and "wayat-python"

We could either change the repo names for quickstart or do the following:

Obtain the list of repositories using the hangar image and the google cloud CLI to generate automatically the buttons for the created repos, making it compatible with as many number of repos with all sorts of names.

If we do this, we could also implement it for other types of resources, such as accesing cloud build, IAM, Firestore, etc.
